name: covid19_dashboard
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  intl: ^0.17.0
  bubble_tab_indicator: ^0.1.6
  http: ^0.13.3
  flutter_svg: ^0.22.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/NotoSansLao-Bold.ttf
    - assets/fonts/NotoSansLao-Regular.ttf
    - assets/fonts/NotoSerifLao-Bold.ttf
    - assets/fonts/NotoSerifLao-Regular.ttf
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg


  fonts:
     - family: NotoSansLao
       fonts:
         - asset: assets/fonts/NotoSansLao-Regular.ttf
         - asset: assets/fonts/NotoSansLao-Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

